--TM_DEFAULT_DATA
--16/06/2017
--BONALDO

insert into plans (fg_active, ds_plan, cd_plan, nm_plan, qt_period, qt_tests, tp_plan, vl_plan) values (1, 'Plano de teste gratuito válido por 30 dias ou até o envio de 30 testes, o que ocorrer primeiro.', 'FREE_PLAN', 'Plano de Teste Gratuito', 30, 30, 'Q', 0);

insert into levels (cd_level, ds_level) values ('JR', 'Junior');
insert into levels (cd_level, ds_level) values ('PL', 'Pleno');
insert into levels (cd_level, ds_level) values ('SR', 'Senior');

INSERT INTO categories (ds_category, cd_category) VALUES ('JavaScript','JS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Java','JAVA');
INSERT INTO categories (ds_category, cd_category) VALUES ('PHP','PHP');
INSERT INTO categories (ds_category, cd_category) VALUES ('C','C');
INSERT INTO categories (ds_category, cd_category) VALUES ('C++','C++');
INSERT INTO categories (ds_category, cd_category) VALUES ('Python','PYTHON');
INSERT INTO categories (ds_category, cd_category) VALUES ('Ruby','RUBY');
INSERT INTO categories (ds_category, cd_category) VALUES ('C#','C#');
INSERT INTO categories (ds_category, cd_category) VALUES ('Swift','SWIFT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Objective-C','OBJECT-C');
INSERT INTO categories (ds_category, cd_category) VALUES ('R','R');
INSERT INTO categories (ds_category, cd_category) VALUES ('Visual Basic','VB');
INSERT INTO categories (ds_category, cd_category) VALUES ('PL/SQL','PLSQL');
INSERT INTO categories (ds_category, cd_category) VALUES ('ASP','ASP');
INSERT INTO categories (ds_category, cd_category) VALUES ('HTML','HTML');
INSERT INTO categories (ds_category, cd_category) VALUES ('CSS','CSS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Design Patterns','DESIGN PATTERNS');
INSERT INTO categories (ds_category, cd_category) VALUES ('SOLID','SOLID');
INSERT INTO categories (ds_category, cd_category) VALUES ('Test Driven Development','TDD');
INSERT INTO categories (ds_category, cd_category) VALUES ('Domain Driven Development','DDD');
INSERT INTO categories (ds_category, cd_category) VALUES ('Mensageria','MENSAGERIA');
INSERT INTO categories (ds_category, cd_category) VALUES ('REST','REST');
INSERT INTO categories (ds_category, cd_category) VALUES ('SOAP','SOAP');
INSERT INTO categories (ds_category, cd_category) VALUES ('Orientação a Objetos','OO');
INSERT INTO categories (ds_category, cd_category) VALUES ('Programação Funcional','PF');
INSERT INTO categories (ds_category, cd_category) VALUES ('HTTP','HTTP');
INSERT INTO categories (ds_category, cd_category) VALUES ('NOSql','NOSQL');
INSERT INTO categories (ds_category, cd_category) VALUES ('Integração Contínua','CI');
INSERT INTO categories (ds_category, cd_category) VALUES ('Deploy Contínuo','CD');
INSERT INTO categories (ds_category, cd_category) VALUES ('User Experience','UX');
INSERT INTO categories (ds_category, cd_category) VALUES ('Servlets','SERVLETS');
INSERT INTO categories (ds_category, cd_category) VALUES ('XML','XML');
INSERT INTO categories (ds_category, cd_category) VALUES ('Json','JSON');
INSERT INTO categories (ds_category, cd_category) VALUES ('Java Enterprise Edition','JEE');
INSERT INTO categories (ds_category, cd_category) VALUES ('Jax-RS','JAX-RS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Jax-WS','JAX-WS');
INSERT INTO categories (ds_category, cd_category) VALUES ('WCF','WCF');
INSERT INTO categories (ds_category, cd_category) VALUES ('SASS','SASS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Compass','COMPASS');
INSERT INTO categories (ds_category, cd_category) VALUES ('LESS','LESS');
INSERT INTO categories (ds_category, cd_category) VALUES ('MySQL','MYSQL');
INSERT INTO categories (ds_category, cd_category) VALUES ('Oracle','ORACLE');
INSERT INTO categories (ds_category, cd_category) VALUES ('SQL Server','SQL SERVER');
INSERT INTO categories (ds_category, cd_category) VALUES ('MongoDB','MONGODB');
INSERT INTO categories (ds_category, cd_category) VALUES ('MariaDB','MARIADB');
INSERT INTO categories (ds_category, cd_category) VALUES ('Cassandra','CASSANDRA');
INSERT INTO categories (ds_category, cd_category) VALUES ('DB2','DB2');
INSERT INTO categories (ds_category, cd_category) VALUES ('Sybase','SYBASE');
INSERT INTO categories (ds_category, cd_category) VALUES ('PostgreSQL','POSTGRESQL');
INSERT INTO categories (ds_category, cd_category) VALUES ('ElasticSearch','ELASTIC SEARCH');
INSERT INTO categories (ds_category, cd_category) VALUES ('Redis','REDIS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Eclipse','ECLIPSE');
INSERT INTO categories (ds_category, cd_category) VALUES ('NetBeans','NETBEANS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Visual Studio','VISUAL STUDIO');
INSERT INTO categories (ds_category, cd_category) VALUES ('Sublime Text','SUBLIME');
INSERT INTO categories (ds_category, cd_category) VALUES ('Atom','ATOM');
INSERT INTO categories (ds_category, cd_category) VALUES ('Brackets','BRACKETS');
INSERT INTO categories (ds_category, cd_category) VALUES ('JDeveloper','JDEVELOPER');
INSERT INTO categories (ds_category, cd_category) VALUES ('Android Studio','ANDROID STUDIO');
INSERT INTO categories (ds_category, cd_category) VALUES ('SQL Developer','SQL DEVELOPER');
INSERT INTO categories (ds_category, cd_category) VALUES ('PL/SQL Developer','PLSQL DEVELOPER');
INSERT INTO categories (ds_category, cd_category) VALUES ('MySQL Workbench','MYSQL WORKBENCH');
INSERT INTO categories (ds_category, cd_category) VALUES ('Notepad++','NOTEPAD++');
INSERT INTO categories (ds_category, cd_category) VALUES ('UltraEdit','ULTRAEDIT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Grunt','GRUNT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Gulp','GULP');
INSERT INTO categories (ds_category, cd_category) VALUES ('Maven','MAVEN');
INSERT INTO categories (ds_category, cd_category) VALUES ('Gradle','GRADLE');
INSERT INTO categories (ds_category, cd_category) VALUES ('GIT','GIT');
INSERT INTO categories (ds_category, cd_category) VALUES ('SVN','SVN');
INSERT INTO categories (ds_category, cd_category) VALUES ('Ant','ANT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Ivy','IVY');
INSERT INTO categories (ds_category, cd_category) VALUES ('Vagrant','VAGRANT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Docker','DOCKER');
INSERT INTO categories (ds_category, cd_category) VALUES ('Jenkins','JENKINS');
INSERT INTO categories (ds_category, cd_category) VALUES ('TravisCI','TRAVIS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Java Server Faces','JSF');
INSERT INTO categories (ds_category, cd_category) VALUES ('Spring','SPRING');
INSERT INTO categories (ds_category, cd_category) VALUES ('Struts','STRUTS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Thymeleaf','THYMELEAF');
INSERT INTO categories (ds_category, cd_category) VALUES ('Java Server Pages','JSP');
INSERT INTO categories (ds_category, cd_category) VALUES ('AngularJS','ANGULARJS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Ember','EMBER');
INSERT INTO categories (ds_category, cd_category) VALUES ('VueJS','VUEJS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Meteor','METEOR');
INSERT INTO categories (ds_category, cd_category) VALUES ('Cordova','CORDOVA');
INSERT INTO categories (ds_category, cd_category) VALUES ('PhoneGap','PHONEGAP');
INSERT INTO categories (ds_category, cd_category) VALUES ('Xamarin','XAMARIM');
INSERT INTO categories (ds_category, cd_category) VALUES ('Ionic','IONIC');
INSERT INTO categories (ds_category, cd_category) VALUES ('Unity','UNITY');
INSERT INTO categories (ds_category, cd_category) VALUES ('Rails','RAILS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Entity Framework','ENTITY FW');
INSERT INTO categories (ds_category, cd_category) VALUES ('Entity LinQ','LINQ');
INSERT INTO categories (ds_category, cd_category) VALUES ('Code Igniter','CODE IGNITER');
INSERT INTO categories (ds_category, cd_category) VALUES ('Laravel','LARAVEL');
INSERT INTO categories (ds_category, cd_category) VALUES ('CakePHP','CAKEPHP');
INSERT INTO categories (ds_category, cd_category) VALUES ('Zend','ZEND');
INSERT INTO categories (ds_category, cd_category) VALUES ('Django','DJANGO');
INSERT INTO categories (ds_category, cd_category) VALUES ('VRaptor','VRAPTOR');
INSERT INTO categories (ds_category, cd_category) VALUES ('Enterprise Java Beans','EJB');
INSERT INTO categories (ds_category, cd_category) VALUES ('Play!','PLAY');
INSERT INTO categories (ds_category, cd_category) VALUES ('.NET','.NET');
INSERT INTO categories (ds_category, cd_category) VALUES ('Bootstrap','BOOTSTRAP');
INSERT INTO categories (ds_category, cd_category) VALUES ('Jersey','JERSEY');
INSERT INTO categories (ds_category, cd_category) VALUES ('JUnit','JUNIT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Selenium','SELENIUM');
INSERT INTO categories (ds_category, cd_category) VALUES ('Java Database Connectivity','JDBC');
INSERT INTO categories (ds_category, cd_category) VALUES ('Java Persistence API','JPA');
INSERT INTO categories (ds_category, cd_category) VALUES ('JQuery','JQUERY');
INSERT INTO categories (ds_category, cd_category) VALUES ('React','REACT');
INSERT INTO categories (ds_category, cd_category) VALUES ('Mean Stack','MEAN');
INSERT INTO categories (ds_category, cd_category) VALUES ('Electron','ELECTRON');
INSERT INTO categories (ds_category, cd_category) VALUES ('Jasmine','JASMINE');
INSERT INTO categories (ds_category, cd_category) VALUES ('JVM','JVM');
INSERT INTO categories (ds_category, cd_category) VALUES ('NodeJS','NODEJS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Linux','LINUX');
INSERT INTO categories (ds_category, cd_category) VALUES ('Windows','WINDOWS');
INSERT INTO categories (ds_category, cd_category) VALUES ('Windows Server','WINDOWS SERVER');
INSERT INTO categories (ds_category, cd_category) VALUES ('Mac','MAC');
INSERT INTO categories (ds_category, cd_category) VALUES ('Android ','ANDROID');
INSERT INTO categories (ds_category, cd_category) VALUES ('IOS','IOS');
INSERT INTO categories (ds_category, cd_category) VALUES ('SQL','SQL');

INSERT INTO parameters (cd_parameter, ds_content, ds_parameter) VALUES ('email.welcome-email', '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Bem vindo ao Trymee!</title> <style type="text/css"> @media(max-width:480px){   table[class=main_table],table[class=layout_table]{width:300px !important;}   table[class=layout_table] tbody tr td.header_image img{width:300px !important;height:auto !important;} } a{color:#37aadc} </style> </head> <body> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tbody> <tr> <td align="center" valign="top"> <!--  M A I N T A B L E  S T A R T  --> <table border="0" cellpadding="0" cellspacing="0" class="main_table" width="600">     <tbody>     <tr>     <td>       <!--  L A Y O U T _ T A B L E  S T A R T  -->     <table border="0" cellpadding="0" cellspacing="0" class="layout_table" style="border-collapse:collapse;border:1px solid #CCCCCC;" width="100%" >       <tbody>       <!--  H E A D E R R O W  S T A R T  -->       <tr>       <td align="left" class="header_image"><img height="64" src="https://s3.amazonaws.com/trymee-files/images/site/header-tm-64-600.png" width="600" style="border:0;display:block;"></td>       </tr>       <!--  H E A D E R R O W  E N D  -->       <tr><td style="font-size:13px;line-height:13px;margin:0;padding:0;">&nbsp;</td></tr>       <!--  B O D Y R O W  S T A R T  -->       <tr>       <td align="center" valign="top">         <table align="center" border="0" cellpadding="0" cellspacing="0" width="85%">           <tbody>           <tr>           <td align="center">             <p style="font-family:Arial, Helvetica, sans-serif;font-size:14px;line-height:22px;"> 				Caro(a) {{name}}, 				<br/> 				<br/> 				Nós do Trymee desejamos as boas vindas e agradecemos o seu cadastro. 				<br/> 				Abaixo estão os detalhes do seu cadastro:             </p> 			<p> 				<table style="font-family:Arial, Helvetica, sans-serif;font-size:14px;line-height:22px;"> 					<tr> 						<td>Login:</td> 						<td>{{email}}</td> 					</tr> 					<tr> 						<td>Plano:</td> 						<td>{{plan}}</td> 					</tr> 					<tr> 						<td>Válido até:</td> 						<td>{{endDate}}</td> 					</tr> 					<tr> 						<td>Quantidade de Testes:</td> 						<td>{{quantity}}</td> 					</tr> 					<tr> 						<td>Preço:</td> 						<td>{{price}}</td> 					</tr> 				</table> 			</p> 			<p style="font-family:Arial, Helvetica, sans-serif;font-size:14px;line-height:22px;"> 				 				Nosso objetivo é tornar os seus processos seletivos mais ágeis e produtivos, e para isso estamos a sua disposição para esclarecer qualquer dúvida e ouvir qualquer dica, crítica ou feedback. Entre em contato conosco respondendo esse e-mail ou envie para contato@trymee.com.br 				<br/> 				<br/> 				Novamente agradecemos a sua confiança e esperamos que a nossa plataforma seja útil e efetiva no seu dia a dia. 				<br/> 				<br/> 				Um grande abraço! 				Equipe Trymee App 			</p>           </td>           </tr>           </tbody>         </table>       </td>       </tr>       <!--  B O D Y R O W  E N D  -->       <tr><td style="font-size:13px;line-height:13px;margin:0;padding:0;">&nbsp;</td></tr>       <!--  F O O T E R R O W  S T A R T        <tr>       <td align="left" class="header_image"><a href="https://www.sparkpost.com/"><img height="67" src="https://www.sparkpost.com/sites/default/files/pictures/email/footer-generic-600x67.png" width="600" style="border:0;display:block;" alt="Sent via SparkPost"></a></td>       </tr> 	  -->       <!--  F O O T E R R O W  E N D  -->       </tbody>     </table>     <!--  L A Y O U T _ T A B L E  E N D  -->     </td>     </tr>     </tbody> </table> <!--  M A I N _ T A B L E  E N D  --> </td> </tr> </tbody> </table> </body> </html>', 'Template do welcome-email');

INSERT INTO parameters (cd_parameter, ds_content, ds_parameter) VALUES ('email.test-link_email', '<p>Caro(a) {{name}},</p>  <p>Este e-mail contém o link para a prova, enviado por {{sender}}. </p>  <p><a href="{{link}}">Clique aqui para iniciar a prova</a></p>  <p>Caso o link acima não esteja disponível, copie e cole o seguinte link no seu navegador: <b>{{link}}</b></p>  <p>Não responda este email. Em caso de dúvidas entre em contato com o recrutador.</p>  <p><a href="http://www.trymee.com.br">TRYMEE APP</a></p>', 'Template para test-link-email');

INSERT INTO parameters (cd_parameter, ds_content, ds_parameter) VALUES ('email.delivery.active', 'A', 'Flag que indica se o envio de emails da plataforma está ativo ou não');